### ISSUE TITLE
undefined method `fog_provider=' for CarrierWave::Uploader::Base:Class (NoMethodError)

### ISSUE THREAD

**Issue by TrevorHinesley** [carrierwaveuploader/carrierwave#1631]
As the title suggests, `fog_provider` isn't working. I'm using Carrierwave 0.10.0 and I have fog-aws installed:

```ruby
CarrierWave.configure do |config|
  config.fog_provider = 'fog-aws'                        # required
  config.fog_credentials = {
    provider:              'AWS',                        # required
    aws_access_key_id:     'xxx',                        # required
    aws_secret_access_key: 'yyy',                        # required
  }
  config.fog_directory  = Rails.env                          # required
end
```

**Comment by plribeiro3000** [comment]
You should be using master. This feature was not release yet i believe.

**Comment by TrevorHinesley** [comment]
Yep that's correct, there's gotta be a better way of showing that the documentation is further along than the current gem version then..

**Comment by TrevorHinesley** [comment]
Now I'm getting:

`/Users/Trevor/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require': cannot load such file -- fog-aws (LoadError)`

**Comment by plribeiro3000** [comment]
Oh. You mean `config.fog_provider = 'fog/aws'`. =)

**Comment by TrevorHinesley** [comment]
Haha yep, the documentation is wrong on that one.

**Comment by plribeiro3000** [comment]
Hmmm. sorry about that. I will send a fix for it asap.

**Comment by eavgerinos** [comment]
For 0.10.0 documentation please see the corresponding [tag](https://github.com/carrierwaveuploader/carrierwave/tree/v0.10.0)

**Comment by eavgerinos** [comment]
Fixed :) Thanks

**Comment by maxkaplan** [comment]
HEY - Just a heads up - This docs are still wrong here - https://github.com/carrierwaveuploader/carrierwave/blob/master/README.md

**Comment by plribeiro3000** [comment]
@maxkaplan Whats wrong on it?

**Comment by maxkaplan** [comment]
@plribeiro3000  

Under 'Using S3' - it still includes 'config.fog_provider = 'fog/aws'

This gave me an error, but seems to work when removed.

We might also want to say 'name_of_bucket' name instead of name_of_directory - it was a little confusing.

Hope this helps,

**Comment by plribeiro3000** [comment]
@maxkaplan Thats the correct one: `config.fog_provider = 'fog/aws'`

Could you provide the error you are getting?

**Comment by maxkaplan** [comment]
I'm running Rails 4.2.1 with mongoid. When I try to start the server I get.

`.../config/initializers/fog.rb:8:in `block in <top (required)>': undefined method `fog_provider=' for CarrierWave::Uploader::Base:Class (NoMethodError)`

But when I remove `config.fog_provider = 'fog/aws'` from my fog.rb initialize it boots fine.

**Comment by plribeiro3000** [comment]
Which version of carrierwave are you using?

**Comment by maxkaplan** [comment]
carrierwave-0.10.0

**Comment by plribeiro3000** [comment]
That documentation you just linked is for master.

For `0.10.0` you should be looking [here](https://github.com/carrierwaveuploader/carrierwave/tree/v0.10.0).

**Comment by maxkaplan** [comment]
Ok so sorry for my confusion. Does the latest (master) work with mongoid and fog-aws? Thanks,

**Comment by plribeiro3000** [comment]
Yep. =)

**Comment by ckonduri** [comment]
Hello Team,

I still see issue.


> Booting WEBrick
=> Rails 4.2.4 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
=> Ctrl-C to shutdown server
Exiting
/Users/chaitanya/yelpdemo/config/initializers/carrierwave.rb:2:in `block in <top (required)>': undefined method `fog_provider=' for CarrierWave::Uploader::Base:Class (NoMethodError)
	from /Users/chaitanya/.rvm/gems/ruby-2.2.1/gems/carrierwave-0.10.0/lib/carrierwave/uploader/configuration.rb:118:in `configure'

My carrierwave.rb file looks like below


CarrierWave.configure do |config|
  config.fog_provider = 'fog/aws'                       # required
  config.fog_credentials = {
    provider:              'AWS',                        # required
    aws_access_key_id:     ‘xxx',                        # required
    aws_secret_access_key: ‘xxx',                        # required
    
  }
  config.fog_directory  = ’bucketname'                          # required
 
end

I had installed gem "fog-aws". Still facing same issue. can some help me to fix this issue?

**Comment by flanger001** [comment]
@plribeiro3000 is right, you have to remove `config.fog_provider`. The `:provider` key in the `config.fog_credentials` hash is where you set AWS.

#### Gemfile
gem 'carrierwave'
gem 'fog'

#### config/initializers/carrierwave.rb
```
CarrierWave.configure do |config|
  config.fog_credentials = {
    # Configuration for Amazon S3
    :provider              => 'AWS',
    :aws_access_key_id     => ENV['S3_KEY'],
    :aws_secret_access_key => ENV['S3_SECRET'],
    :region                => ENV['S3_REGION']
  }

  config.cache_dir = "#{Rails.root}/tmp/uploads"
  config.fog_directory  = ENV['S3_BUCKET_NAME']
  config.fog_public     = false
  config.fog_attributes = { 'Cache-Control' => "max-age=#{365.day.to_i}" }
  config.storage = :fog
end

This setup is presently working for me on carrierwave-0.10.0

**Comment by plribeiro3000** [comment]
Actually the `config.fog_provider` is only needed when you don´t have `fog` but only one of the providers (in this case `fog-aws`).

The issue @ckonduri is facing is because he is looking into the wrong documentation.
See [here](https://github.com/carrierwaveuploader/carrierwave/tree/v0.10.0) for the expected configurations for you @ckonduri .

**Comment by dijonkitchen** [comment]
I recently had this problem. Would it be better to either update the gem or default the branch shown for the github page to 0.10.0?

Not everyone would see this message at the top of the readme since it's so comprehensive: https://github.com/carrierwaveuploader/carrierwave#carrierwave-version-disclaimer
