### ISSUE TITLE
Warnings when running specs on CI

### ISSUE THREAD

**Issue by thomasfedb** [carrierwaveuploader/carrierwave#1814]
When running specs, the following warnings are generated:

JRuby only:

```
file:/home/travis/.rvm/rubies/jruby-1.7.19-d19/lib/jruby.jar!/jruby/kernel19/kernel.rb:28 warning: unsupported exec option: close_others
```

JRuby only:

```
/home/travis/.rvm/gems/jruby-1.7.19-d19/gems/fog-aws-0.7.6/lib/fog/aws/storage.rb:6 warning: already initialized constant COMPLIANT_BUCKET_NAMES
/home/travis/.rvm/gems/jruby-1.7.19-d19/gems/fog-aws-0.7.6/lib/fog/aws/storage.rb:8 warning: already initialized constant DEFAULT_REGION
/home/travis/.rvm/gems/jruby-1.7.19-d19/gems/fog-aws-0.7.6/lib/fog/aws/storage.rb:10 warning: already initialized constant DEFAULT_SCHEME
/home/travis/.rvm/gems/jruby-1.7.19-d19/gems/fog-aws-0.7.6/lib/fog/aws/storage.rb:11 warning: already initialized constant DEFAULT_SCHEME_PORT
/home/travis/.rvm/gems/jruby-1.7.19-d19/gems/fog-aws-0.7.6/lib/fog/aws/storage.rb:16 warning: already initialized constant VALID_QUERY_KEY
```

Rails 4.2 only:

```
DEPRECATION WARNING: Currently, Active Record suppresses errors raised within `after_rollback`/`after_commit` callbacks and only print them to the logs. In the next version, these errors will no longer be suppressed. Instead, the errors will propagate normally just like in other Active Record callbacks.
You can opt into the new behavior and remove this warning by setting:
  config.active_record.raise_in_transactional_callbacks = true
```

**Comment by mehlah** [comment]
I just PRed #1815 with a fix for AR depreciation warnings when running the cucumber suite.

The first JRuby warning you mention can't be fixed by us. It's a Bundler issue that seems fixed but not yet released (ref https://github.com/jruby/jruby/issues/1913)

The other JRuby warnings about already defined constants comes from fog-aws gem (see fog-aws build log for almost the same warnings https://travis-ci.org/fog/fog-aws/jobs/90557832).
Same thing, can't be fixed by us :wink:

**Comment by thomasfedb** [comment]
Issues with `Fog::Aws` discussed here: https://github.com/fog/fog-aws/issues/212

**Comment by mshibuya** [comment]
Checked the current CI (JRuby 10.1.1.0 / Ruby 2.7–4.0 / ruby-head, GitHub Actions): none of the warnings listed here still occur — they were tied to JRuby 1.7, fog-aws 0.7.6, and Rails 4.2, all long gone.

CI wasn't fully warning-free though: the JRuby job had ~75 "literal string will be frozen in the future" warnings, from a couple of our own specs handing literal strings to code that mutates them in place (`IO#read`'s `outbuf`, and fog-core's `force_encoding` on a mocked file body). Fixed in 4593093.

MRI/ruby-head jobs are clean. Closing.
