### ISSUE TITLE
Upload fails when calling ActiveRecord model 'dup' with after_create or after_update.

### ISSUE THREAD

**Issue by macera** [carrierwaveuploader/carrierwave#2700]
Upload fails when calling ActiveRecord model 'dup' with after_create or after_update.
since version 3.0.0rc

e.g.
[counter_culture](https://github.com/magnusvk/counter_culture)
calls dup on after_create, after_update.

**Comment by rajyan** [comment]
See https://github.com/carrierwaveuploader/carrierwave/issues/2689

I think it's fixed in the latest release (3.0.3).

**Comment by rajyan** [comment]
Sorry, it wasn't released yet...

**Comment by macera** [comment]
Tnanks for letting me know [#2689](https://github.com/carrierwaveuploader/carrierwave/issues/2689) !
It is the same problem.
But I checked on the master branch and the issue was not fixed...

After calling ActiveRecord model 'dup' with `after_create` or `after_update`, 
`@cache_id=nil` happens with `after_save`.

carrierwave/lib/carrierwave/uploader/store.rb
```
def store!(new_file=nil)
  cache!(new_file) if new_file && !cached?
  puts @cache_id #=> nil
  if !cache_only && @file && @cache_id
    with_callbacks(:store, new_file) do
      new_file = storage.store!(@file)
      ...
```
Therefore, it cannot be uploaded.

**Comment by rajyan** [comment]
> But I checked on the master branch and it isn't fixed...

I confirmed the behavior and you are right. https://github.com/carrierwaveuploader/carrierwave/issues/2689 fixed some parts of `dup`, but model with counter_culture still doesn't work (especially on first upload).

**Comment by rajyan** [comment]
> But I checked on the master branch and it isn't fixed...

You're right. I've confirmed that using `counter_cluture` with carrierwave still doesn't work event after fixing `dup` bug in 
https://github.com/carrierwaveuploader/carrierwave/pull/2690 .

The file key is persisted to the DB, but is not stored to the storage.

**Comment by rajyan** [comment]
@macera 

 Could you please try whether [this](https://github.com/carrierwaveuploader/carrierwave/issues/2700) patch fixes your issue?

**Comment by macera** [comment]
@rajyan 
Ohhhh...! I've confirmed that the problem has been fixed !

**Comment by macera** [comment]
@mshibuya 
Do you have a plan for the next release that includes this fix?
I'd appreciate it if you could let me know when.

**Comment by mshibuya** [comment]
Just released 3.0.4 now! 🚀
